# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: webapp4

resources:
  repositories:
    - repository: WebApplication1
      type: github
      name: v3lli/WebApplication1
      endpoint: github.com_v3lli

extends:
  template: azure-pipelines.yml@WebApplication1
  parameters:
      iispath: $(diapath)
      pspwd: $(Password)
      appname: $(Webapp)